version: 2
project_name: resticm

before:
  hooks:
  - go mod tidy
  - go test ./...

builds:
- id: resticm
  main: ./main.go
  binary: resticm
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  - "386"
  - arm
  goarm:
  - "6"
  - "7"
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X resticm/cmd.version={{.Version}}
  - -X resticm/cmd.commit={{.Commit}}
  - -X resticm/cmd.buildDate={{.Date}}
  flags:
  - -trimpath

archives:
- id: resticm
  formats: [ "tar.gz" ]
  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
  wrap_in_directory: true
  files:
  - LICENSE
  - README.md
  - config.example.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^ci:"
    - "^chore:"
    - "^build:"
  groups:
  - title: Features
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: Bug fixes
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: Others
    order: 999

# Release configuration
release:
  github:
    owner: Gu1llaum-3
    name: resticm
  prerelease: auto
  draft: false
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Resticm {{.Version}}

    Thank you for downloading Resticm!

  footer: |
    ## Installation

    ### Quick Install (Recommended)

    Install the latest version with a single command:

    ```bash
    curl -sSL https://raw.githubusercontent.com/Gu1llaum-3/resticm/main/install/unix.sh | bash
    ```

    **Install this specific version:**

    ```bash
    RESTICM_VERSION={{.Tag}} curl -sSL https://raw.githubusercontent.com/Gu1llaum-3/resticm/main/install/unix.sh | bash
    ```

    **Custom installation directory:**

    ```bash
    INSTALL_DIR=/opt/bin curl -sSL https://raw.githubusercontent.com/Gu1llaum-3/resticm/main/install/unix.sh | bash
    ```

    ### Manual Installation

    Download the appropriate binary for your platform from the assets above, extract it, and place it in your PATH:

    ```bash
    # Example for Linux amd64
    tar -xzf resticm_Linux_x86_64.tar.gz
    cd resticm_Linux_x86_64
    sudo mv resticm /usr/local/bin/
    sudo chmod +x /usr/local/bin/resticm
    ```

    ### From Source

    ```bash
    git clone https://github.com/Gu1llaum-3/resticm.git
    cd resticm
    make build
    sudo make install
    ```

    ### Prerequisites
    - [restic](https://restic.net/) must be installed and available in your PATH
    - Go 1.24+ (for building from source only)

    ## Quick Start

    1. Create configuration:
    ```bash
    mkdir -p ~/.config/resticm
    cp config.example.yaml ~/.config/resticm/config.yaml
    chmod 600 ~/.config/resticm/config.yaml
    ```

    2. Initialize repository:
    ```bash
    resticm init
    ```

    3. Run your first backup:
    ```bash
    resticm
    ```

    ## Full Changelog

    See all changes at https://github.com/Gu1llaum-3/resticm/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    📖 **Documentation:** See the updated [README](https://github.com/Gu1llaum-3/resticm/blob/main/README.md)

    🐛 **Issues:** Found a bug? Open an [issue](https://github.com/Gu1llaum-3/resticm/issues)

    ---

    Released with ❤️ by [GoReleaser](https://github.com/goreleaser/goreleaser)

# Snapshot builds (for non-tag builds)
snapshot:
  version_template: "{{ .Tag }}-snapshot-{{.ShortCommit}}"

# Metadata for package managers
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
